### ISSUE TITLE
ArrayCollection::matching not doing multiple field sort

### ISSUE THREAD

**Issue by trickeyone** [doctrine/collections#106]
There appears to be a couple pull requests from 2 years ago that have been merged but never added to a release (#59 & #64) that fixes the very issue I'm having: sorting an ArrayCollection by multiple fields. When can we expect a new release including these fixes? 2 years is kind of a long time to wait for this basic fix.

**Comment by mikeSimonson** [comment]
Thanks for the reminder.

Done
