### ISSUE TITLE
Bumping the Version without Releasenotes V1.4

### ISSUE THREAD

**Issue by ohartl** [doctrine/collections#109]
I think there may have been a mistaken release of V1.4 on 2017-01-03 by @mikeSimonson 

* The tagged version is not conform with the previous version
* There are no release notes
* Changes from over a year (`v1.3.0` was released in 2015-04-15

Could you at least write some release notes, please? This library is used by a ton of people..

**Comment by mikeSimonson** [comment]
@ohartl Well I didn't wrote any release note because it was really hard to get something comprehensible with so many changes. I might try it again but when I have some time to look into it.

**Comment by mikeSimonson** [comment]
@ohartl @Ocramius Done.

It should be complete https://github.com/doctrine/collections/releases/tag/v1.4.0
