### ISSUE TITLE
question regarding Closure

### ISSUE THREAD

**Issue by bashilbers** [doctrine/collections#117]
Hi,

Why does the `Collection` interface depend `Closure` (e.g. for the `fillter` method) instead of `callable`?

Just a simple usecase: using classes with `__invoke` to filter a collection.

(happy to help here)

**Comment by lcobucci** [comment]
@bashilbers I'm not sure but it sounds like for historical reasons (and BC).

`Closure` was added in PHP 5.3 and `callable` in PHP 5.4 and changing the type-hint on the interface would be a BC-break...

We can think of doing that for our next major release, though.

**Comment by bashilbers** [comment]
Makes sense. Is there a roadmap? I would like to contribute for the next major release.

**Comment by Ocramius** [comment]
No roadmap for collections yet: as far as I can see, changing collections
is a huge issue, so it will likely stay as-is while we develop a new
package with a different API instead...

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

On Wed, May 3, 2017 at 8:48 AM, Sebastiaan Hilbers <notifications@github.com

**Comment by bashilbers** [comment]
Closing this due to the reason that BC forces it to stay the way it is now
