### ISSUE TITLE
Collections/ExpressionBuilder::contains generate CONTAINS instead of LIKE in MySQL

### ISSUE THREAD

**Issue by holantomas** [doctrine/collections#140]
Hi,
I found that if I try to filter over PersistentCollection using contains(there's no `LIKE` like in query builder) it throws SQL Error cause used key word **CONTAINS** instead of **LIKE** in **WHERE** conditions.

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CONTAINS '%dsadas%' ...' at line 1

```

Is BUG or my miss-understand ?

https://github.com/doctrine/collections/blob/master/lib/Doctrine/Common/Collections/ExpressionBuilder.php#L145

**Comment by Ocramius** [comment]
@holantomas `CONTAINS` is correct there, but the visitor used to convert the criteria into an SQL statement needs to be checked. Please do reproduce the issue in an isolated test case like the ones in https://github.com/doctrine/doctrine2/tree/master/tests/Doctrine/Tests/ORM/Functional/Ticket

**Comment by Ocramius** [comment]
Closing here: the bug is not in `doctrine/collections`.
