### ISSUE TITLE
ArrayCollection->filter() should use array_values

### ISSUE THREAD

**Issue by alexbonhomme** [doctrine/collections#141]
Hi everyone !

I am facing a bug using `ArrayCollection->filter()`. As it use `array_filter` internally, the `elements` attribute of the collection is an associative array after the filter. 
Because `array_filter` removes elements without reindexing keys, we should use `array_values` to avoid serialization problem (due to associative array, instead of pure array).

The fix is relatively easy to apply and shouldn't create any problem.

```php
public function filter(Closure $p)
{
    return $this->createFrom(array_values(array_filter($this->elements, $p)));
}
```

What did you think about ?

**Comment by Ocramius** [comment]
@alexbonhomme disagree for two reasons here:

 1. modifies existing behavior in a subtle way that is difficult to detect other than from `UPGRADE.md`
 2. a collection has keys by design: the fact that you are treating the collection as an array is a different question
