### ISSUE TITLE
Question: Why ArrayCollection doesn't implement Traversable

### ISSUE THREAD

**Issue by shehi** [doctrine/collections#145]
According to PHP [website](http://php.net/manual/en/language.types.iterable.php), ```iterable```s are whatever implements ```Traversable``` interface. Setting method parameter-types/return-types as ```iterable``` helps a lot, but ```ArrayCollection``` not implementing that interface, creates a problem.

So my question is: technically being traversable, why Doctrine collections do not implement this interface, to make them "legally" ```iterable```?

Thanks.

**Comment by Ocramius** [comment]
@shehi implementing `Traversable` can only be done by either implementing `Iterator` or `IteratorAggregate`. `Collection` already does that: https://github.com/doctrine/collections/blob/f489500ba873f8ab20b94e4a1873ff6457f84914/lib/Doctrine/Common/Collections/Collection.php#L27

**Comment by shehi** [comment]
I already know that @Ocramius . But official documentation doesn't really say that implementations of ```IteratorAggregate``` are considered ```iterable```s. On a different note - when it [documents](http://php.net/manual/en/class.traversable.php) ```Traversable``` it just says:

> Internal (built-in) classes that implement this interface can be used in a ```foreach``` construct and do not need to implement ```IteratorAggregate``` or ```Iterator```.

And of course this note has nothing to do with ```iterable``` type. If you noticed, my concern is specifically about this "type". Otherwise, if you read in my OP, I already said "technically being traversable" already.

**Comment by Ocramius** [comment]
https://3v4l.org/ios53

```php
<?php

class Foo implements IteratorAggregate { public function getIterator() { return new ArrayIterator([]); }}

function foo(iterable $bar) { var_dump($bar); }

foo(new Foo());
```
