### ISSUE TITLE
Bug in Criteria documentation

### ISSUE THREAD

**Issue by flaushi** [doctrine/collections#148]
Hi,
I had a problem with Criteria, which was solved for me on [stackoverflow](https://stackoverflow.com/questions/49450970/get-elements-from-lazyloadcollection/49630107#49630107).
The bottom line was an inconsistency between the [code](https://github.com/doctrine/collections/blob/v1.5.0/lib/Doctrine/Common/Collections/Criteria.php#L193) in the [docs](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/query-builder.html#adding-a-criteria-to-a-query), which I just wanted to forward to you.
Best regards,
Oliver

**Comment by malarzm** [comment]
Fixed in https://github.com/doctrine/doctrine2/pull/7173. Thanks @flaushi for the report!
