### ISSUE TITLE
ArrayCollection should have initilized $elements property

### ISSUE THREAD

**Issue by Arkemlar** [doctrine/collections#155]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | v1.5.0 (doctrine/collections)

#### Summary

ArrayCollection class has unitialised private `$elements` property which leads to `null` value in it in some cases. 
It needs to be initialized:
`private $elements;` => `private $elements = [];`

#### Current behavior

In case of deserialization the value of the property is not safty - it might be `null`! As the result - I getting error exception when calling ArrayCollection's methods which contains inner calls to php functions with array only arguments (e.g. `getValues()` calls ` array_values()`).

#### How to reproduce

1. Extend ArrayCollection, and implement /Serializable interface (add custom seialize and userialize methods).
```
class ExtendedArrayCollectionWithCustomSerializer extends ArrayCollection implements Serializable
{
    public function serialize()
    {
        return json_encode($this->getKeys());
    }

    public function unserialize($serialized)
    {
        // $this->clear(); // Workaround to force $elements initialisation

        foreach (json_decode($serialized) as $value) {
            parent::add($value);
        }
    }
}
```

2. Create an **empty** ArrayCollection instance, then serialize and userialize it, then check unserialized instance - it will have `null` value in `$elements` property. 
3. Call something like `getValues()` you will get an error: `Warning: array_values() expects parameter 1 to be array, null given`

```
$collection = new ExtendedArrayCollectionWithCustomSerializer();
$collection = unserialize(serialize($collection));
// At this point $collection->elements === null
$collection->getValues();  // ErrorException there: Warning: array_values() expects parameter 1 to be array, null given
```

#### Expected behavior

Have `$elements` property either protected or initilized so we can write safety deserialization code (and therefore never get `null` as `$elements` property value)

**Comment by Ocramius** [comment]
@Arkemlar can you maybe make an example to be added to https://github.com/doctrine/collections/blob/ab12b39de988ee3d80bf2d5f16b1161ee5fb2529/tests/Doctrine/Tests/Common/Collections/ArrayCollectionTest.php?

**Comment by Arkemlar** [comment]
Yep, next week.
