### ISSUE TITLE
Separate interface documentation for Collection and Selectable

### ISSUE THREAD

**Issue by alcaeus** [doctrine/collections#156]
The [documentation for the collection interface](https://www.doctrine-project.org/projects/doctrine-collections/en/latest/index.html#matching) lists the `matching` method along with all other methods even though it isn't included in the same interface but in the `Selectable` interface. This came up during https://github.com/phpstan/phpstan-doctrine/pull/33.

**Comment by SenseException** [comment]
PR got merged and the separation of `Collection` and `Selectable` is deployed.
