### ISSUE TITLE
ArrayCollection preserves keys in numeric arrays

### ISSUE THREAD

**Issue by apapsch** [doctrine/collections#169]
This seems somewhat related to #642, so I guess the problem is already known, but anyway: The following code produces unexpected results:

    $c = new Doctrine\Common\Collections\ArrayCollection();
    $c->add(42);
    $c->remove(0);
    $c->add(42);
    var_dump($c->get(0));

Expected output: 42
Actual output: NULL

Now, one could argue, this is PHP insanity dragged into Doctrine, so work around it yourself. Fair enough:

    var_dump(array_values($c->toArray())[0]); // => 42
    var_dump($c->getIterator()->current()); // => 42
    // Funnily, this fails:
    var_dump($c->getIterator()->seek(0)); // => NULL

IMHO, Doctrine should ensure numbering starting from 0 without holes in numeric arrays. But I suspect this won't be done, because the distinction numeric vs. associative is purely context dependent, because the internal array representation is always a hash map?

**Comment by Ocramius** [comment]
At this stage, this would be a BC break, sadly.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Ocramius** [comment]
Unlikely gonna happen: if we modify the collection API (if at all, given the amount of coupling to it from userland), then we'll likely move to php-ds instead

**Comment by Ocramius** [comment]
Note that your approach wouldn't (for example) work within ORM/ODM context, since there's no way to define what type of map/stack/list/etc should be used

**Comment by malarzm** [comment]
@apapsch you may want to see https://github.com/malarzm/collections for some more implementations of `Collection` interface.

@Ocramius actually in ODM you can use custom collection class :)

**Comment by apapsch** [comment]
Yay, `ListArray` sounds just about right, thanks for the hint. I'll look into integration shortly. In the meantime I'll close this issue, now that extension outside of doctrine/collections is more viable.
