### ISSUE TITLE
RFC: Expanding Collections Library

### ISSUE THREAD

**Issue by schmittjoh** [doctrine/collections#171]
I'm wondering if there was any specific reason to go with a single "Collection" class instead of implementing more sophisticated sub-classes like:
- Maps: Elements are stored by key (currently `Collection::set()`)
- Lists: Elements are simply appended (currently `Collection::add()`)
- Sets: Like lists, but guarantees no duplicate elements (currently no equivalent)

**Comment by Ocramius** [comment]
Closing due to strict relation with https://github.com/doctrine/collections/issues/172. I think we should think about allowing arbitrary data structures, instead of forcing our own collection API.

Tricky, but not unfeasible. For this particular repository, no action is required.
