### ISSUE TITLE
V1.6.0 throws errors in Symfony context

### ISSUE THREAD

**Issue by elmariachi111** [doctrine/collections#180]
Using API platform.

After the update to 1.6.0 cache:clear throws an error:

```
Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the dev environment with debug                       
!!   // true                                                                        
!!  
!!  
!!  In FileLoader.php line 166:
!!                                                                                 
!!    [Semantical Error] The annotation "@template" in class Doctrine\Common\Coll  
!!    ections\Collection was never imported. Did you maybe forget to add a "use"   
!!    statement for this annotation? in . (which is being imported from "/srv/api  
!!    /config/routes/api_platform.yaml"). Make sure there is a loader supporting   
!!    the "api_platform" type.                                                     
!!                                                                                 
!!  
!!  In AnnotationException.php line 54:
!!                                                                                 
!!    [Semantical Error] The annotation "@template" in class Doctrine\Common\Coll  
!!    ections\Collection was never imported. Did you maybe forget to add a "use"   
!!    statement for this annotation?                                               
!!                                                                                 
!!  
```

config/routes/api_platform.yml
```yml
api_platform:
    resource: .
    type: api_platform
```

Origin: 
`@template T` in https://github.com/doctrine/collections/commit/7ddac104668249f0f4803b128eb30d0564467a68#diff-6ecd3b230c9f7cef1a38ea4da84278f3R27

After manually fixing doctrine/collection in composer.json to 1.5.0 it works again.

**Comment by Ocramius** [comment]
As noted in https://github.com/doctrine/collections/pull/177#issuecomment-472467691, scavenging `vendor/` for annotations is not a good idea. This is an issue to be reported in APIPlatform.

**Comment by stof** [comment]
Well, multiple Symfony component needs to be able to read metadata (potentially using annotations) from arbitrary classes (Validator and Serializer are the one coming to my mind right now).
And at least for these 2 components, it is very common to use them on object graphs involving Doctrine collections (as a common use case is to use them on your entities).
Most of the time, you won't need any metadata there, as you want to treat the collection with the standard handling of Traversable. But this does not mean that Symfony forbids defining a custom behavior, and so it still tries to find the metadata.

The fix for that would be to ignore the Psalm-specific tags in doctrine/annotations by default, as is done already for phpdoc tags.

**Comment by stof** [comment]
hmm, regarding `@template` itself, ignoring it might cause issues with the `\Sensio\Bundle\FrameworkExtraBundle\Configuration\Template` annotation though, in case the ignore list is case sensitive

**Comment by Ocramius** [comment]
Can you check if #186 fixes this, or if we still need to ignore these annotations?

**Comment by stof** [comment]
this won't fix it, as doctrine/annotations will still complain. But it will make it simpler to ignore it by default.

**Comment by Ocramius** [comment]
Interesting that it parses `@psalm` - easier to skip indeed though :)

**Comment by stof** [comment]
@Ocramius doctrine/annotation will parse everything starting with `@`, unless explicitly configured to be ignored. That's how it works, so that it can report mistakes where you forgot to import the annotation.

**Comment by Ocramius** [comment]
Yeah, currently patching `doctrine/annotations`, since `-` is not a valid class identifier anyway

**Comment by stof** [comment]
hmm, automatically excluding anything containing a `-` indeed solves it pretty nicely.

**Comment by trompette** [comment]
Time to revive https://wiki.php.net/rfc/annotations or https://wiki.php.net/rfc/annotations_v2 ! :wink:

**Comment by Ocramius** [comment]
@trompette this has nothing to do with the current problem.

**Comment by Ocramius** [comment]
Meanwhile, re-opening here, while working on the issue :+1:

**Comment by Ocramius** [comment]
I've provided doctrine/annotations#257 - give it a shot please :)

**Comment by jverdeyen** [comment]
Still has this error for me when using dev-master using it in a Symfony 4.2 app.

```
[Semantical Error] The annotation "@psalm" in class Doctrine\Common\Collections\AbstractLazyCollection was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

**Comment by greg0ire** [comment]
Using `dev-master`, will not help, this is not merged yet. @Ocramius, https://twitter.com/greg0ire/status/1089973726429499392?s=20

**Comment by bvisonl** [comment]
![image](https://user-images.githubusercontent.com/4421747/54944699-7dc76e80-4f0a-11e9-936f-ecd749d693eb.png)

Happening to me as well.

**Comment by greg0ire** [comment]
@jverdeyen it is merged now, but in the 1.6 branch.

**Comment by Ocramius** [comment]
Handled and tested: preparing release.

**Comment by Ocramius** [comment]
Please note: you'll need `doctrine/collections` `1.6.1` along with `doctrine/annotations` `1.6.1`.
