### ISSUE TITLE
Issue with @template annotation on AbstractLazyCollection

### ISSUE THREAD

**Issue by julien-maurel** [doctrine/collections#184]
hi,
I update doctrine collections to 1.6 this morning and following exception is throw during my tests :
[Semantical Error] The annotation "@template" in class Doctrine\Common\Collections\AbstractLazyCollection was never imported. Did you maybe forget to add a "use"...

I use doctrine bundle with symfony 4.2, and mapping configuration for my entites use type "annotation"

I think template and template-implements annontations whould be in annotations to ignore on AnnotationReader.
Else do you have any ideas to not have this issue?

**Comment by Ocramius** [comment]
Duplicate of https://github.com/doctrine/collections/issues/180
