### ISSUE TITLE
[Question] Why doesn't this package use the Data Structures (DS) extension?

### ISSUE THREAD

**Issue by CViniciusSDias** [doctrine/collections#191]
The Data Structures (DS) extension comes with an awesome interface and killing performance. Why not to use it? There's even a polyfill for when the client doesn't want to add a new extension.

**Comment by Ocramius** [comment]
I'd rather say that `ext-ds` is a replacement of collections, and not an implementation detail.

As for performance impact: that depends on what you do. If you use it as implementation detail of `Coolections`, the performance impact is negligible, and highly shadowed by the userland method calls (even for `O(n)`) for the grand majority of use-cases.
