### ISSUE TITLE
The annotation "@psalm" in [...] was never imported

### ISSUE THREAD

**Issue by iammichiel** [doctrine/collections#198]
Hi, 

After upgrading to the latest version of 1.6.1, the following error is thrown : 

```
[Semantical Error] The annotation "@psalm" in class Doctrine\Common\Collections\AbstractLazyCollection was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

I suppose the `@psalm` annotation does exist but in the `vimeo/psalm` package which is only required in the `require-dev` section. Any idea how to correct this ? 

Rolling back to 1.5.x for the moment.

**Comment by alcaeus** [comment]
See https://github.com/doctrine/collections/issues/180#issuecomment-475998757 and the following discussion. IIRC we released doctrine/annotations 1.6.1 which fixes this issue as well. What version are you running?

**Comment by Ocramius** [comment]
Please upgrade `doctrine/annotations`: already fixed there.

**Comment by iammichiel** [comment]
Thanks for the quick answer. I think however, you mixed up the package names in the changelog. 

I pushed a PR to correct the name of the related package in changelog 1.6.1. to `annotations` which makes more sense now :)
