### ISSUE TITLE
Array Filter change collecion index

### ISSUE THREAD

**Issue by ping86** [doctrine/collections#207]
In this file:

https://github.com/doctrine/collections/blob/master/lib/Doctrine/Common/Collections/ArrayCollection.php#L341

```
    public function filter(Closure $p) : Collection
    {
        return $this->createFrom(array_filter($this->elements, $p, ARRAY_FILTER_USE_BOTH));
    }
```

When you filter the array collection the php array keys change.

Original array
{
[0] =>
[1] => 
[2] =>
}

When you filter the array and filter the 1 element, this is the result

Original array
{
[0] =>
[2] =>
}

Is possible change this behavior?

We can add array_values function

Change
        return $this->createFrom(array_filter($this->elements, $p, ARRAY_FILTER_USE_BOTH));

by

        return $this->createFrom(array_values(array_filter($this->elements, $p, ARRAY_FILTER_USE_BOTH)));

Thanks.

**Comment by malarzm** [comment]
You can use `->filter(/* ... */)->getValues()` to achieve what you want
