### ISSUE TITLE
Pluck Property on collection list

### ISSUE THREAD

**Issue by yassinechabli** [doctrine/collections#208]
Q | A
-- | --
Branch? | master
Bug fix? | non
New feature? | yes
Deprecations? | no

what about to add a new feature in the arrayCollection to pluck only property from the object collection list .

example :

~~~~~
class foo {
   protected $id;
   $protected $bar; 
  public function __construct($id , $name)
  {
      $this->id = $id;
      $this->name= $name; 
  }
}
$collection = new ArrayCollection([new foo(1), new foo(2)]);
$propertiesValue = collection->pluck("id");  // [1,2] array or collection 
~~~~~

i already work on this feature , if it seems to be useful , i can work on it .

**Comment by malarzm** [comment]
I'm 👎 as passing a property name doesn't tell us how to get a property out of an object (so we'll need to check public access, getter, reflection). Also tooling won't be able to find usages of a property/method as it's hidden behind "magical" access.

**Comment by yassinechabli** [comment]
i see that there accurate cases that can be handled. 
**The first easy one**  
When handling a collection of object that has the getter of the property in question => easy to get the property value.
 **The second case**
if the object class has only __get method => the function pluck will handle a lot of cases .


In general ,I think using reflection could resolve the problem in all cases . 

i'm a wrong ?

**Comment by someniatko** [comment]
IMO an abstract collection should not depend on type of its underlying element.

**Comment by lcobucci** [comment]
Agreed, this isn't a fit for this library since it involves object introspection and might potentially break encapsulation.

I think that the benefits are very limited, so will close this as "won't fix".
