### ISSUE TITLE
Invalid psalm type inference for ArrayCollection#map()

### ISSUE THREAD

**Issue by someniatko** [doctrine/collections#210]
Similar to #200 but about `map()` method.

I have created a reproduction repository: https://github.com/someniatko/doctrine-collections-map-psalm

doctrine/collections: v1.6.2
vimeo/psalm: 3.6.2

**Comment by greg0ire** [comment]
I'm afraid v1.6.2 does not contain the fixed for #200 , but I could be wrong, please check.

**Comment by someniatko** [comment]
@greg0ire strange, the issue has milestone 1.6.2

**Comment by greg0ire** [comment]
That's correct! I'm not sure why v1.6.2 does not show up on this page: https://github.com/doctrine/collections/commit/59451730480c1d87f777a3a4cee4653251be8457 , but `git tag --contains 59451730480c1d87f777a3a4cee4653251be8457` says you're correct!

**Comment by someniatko** [comment]
@Ocramius Hasn't 1.6.2 already been released?
https://github.com/doctrine/collections/releases/tag/v1.6.2

**Comment by Ocramius** [comment]
Aye, milestone is wrong, thanks for noticing!
