### ISSUE TITLE
v1.6.2 release is not included in the changelog

### ISSUE THREAD

**Issue by someniatko** [doctrine/collections#212]
The latest version listed in the README.md's Changelog section is v1.6.1. This already had led to confusion when picking the milestone for https://github.com/doctrine/collections/issues/210.

Also, as a side question, when is v1.6.3 estimated to be released?

**Comment by Ocramius** [comment]
I think we should stop putting the changelog into a file, unless we automate its generation.

As for 1.6.3, seems ready to release, it will eventually happen 👍
