### ISSUE TITLE
Classes extending ArrayCollection getting psalm errors since psalm 3.6.6

### ISSUE THREAD

**Issue by sspat** [doctrine/collections#223]
Considering this code:
```php
<?php

use Doctrine\Common\Collections\ArrayCollection;

$extendedCollection = new class ([]) extends ArrayCollection {};
$extendedCollection->filter(fn () => true);
```

Since this change in psalm released in version 3.6.6:
https://github.com/vimeo/psalm/issues/2326

When analyzing the code above with psalm I get the following error:
```
ERROR: TooManyTemplateParams - src/Application/test.php:6:1 - _var_www_src_Application_test_php_5_87 has too many template params, expecting 0
$extendedCollection->filter(fn () => true)
```

**Comment by Ocramius** [comment]
I don't think this is a bug with `doctrine/collections` per-se: suggest reproducing with a minimal scenario (without `doctrine/collections`) and reporting upstream.

**Comment by sspat** [comment]
Thank you, will continue there! That one was tricky to reproduce in isolation.

**Comment by muglug** [comment]
So it _sort_ of is - at least, since that PR, `@return static<TKey, TValue>` is unnecessary (and can generate errors) whereas `@return static` now works. But I'll add a workaround.

**Comment by muglug** [comment]
This can be closed now

**Comment by greg0ire** [comment]
Thanks!
