### ISSUE TITLE
ClosureExpressionVisitor::getObjectFieldValue() camelcase issue

### ISSUE THREAD

**Issue by delormejonathan** [doctrine/collections#225]
We are trying to filter an entity relation with a Doctrine Criteria

```
    /**
     * @ORM\OneToMany(targetEntity="Message")
     */
    private $messages;

    public function getMessagesWithCriteria() {
        $criteria = new Criteria();
        $criteria->where(Criteria::expr()->eq('field', 'value'));
        return $this->messages->matching($criteria);
    }
```
In a controller when you call first the original relation getMessages() and then the filtered relation getMessagesWithCriteria() like this :

```
$mainEntity->getMessages()->last()->getId();
$mainEntity->getMessagesWithCriteria()->last()->getId();
```
The ClosureExpressionVisitor is causing an exception by calling the property with a bad accessor "getfield()" instead of "getField()"
The ClosureExpressionVisitor is not camel casing the field name line 58 :

`$accessor = $accessors[0] . $field;`

Is the parameter $field in `ClosureExpressionVisitor::getObjectFieldValue($object, $field)` must be already in camelcase or in lowercase ?

**Comment by SenseException** [comment]
Hi @delormejonathan, I'm not able to recreate this behaviour. Can you please provide a failing test that shows this error?
Which version of Collections are you using?

**Comment by delormejonathan** [comment]
Hello,

After re-creating a sample example with Symfony Standard Edition, I found my issue.
The ClosureExpressionVisitor is calling `method_exists` without camelcasing the function name because PHP is case unsensitive with the method names. (https://stackoverflow.com/questions/2749781/why-are-functions-and-methods-in-php-case-insensitive)

I am using a library based on the magic __call function which is case sensitive for the function name, so I hit this error.

Even if I think that it's a little bit weird to call "methods_exists" without camelcasing the function name, this issue does not belong to this repository.

Thank you !
