### ISSUE TITLE
How to search in the multidimensional array ?

### ISSUE THREAD

**Issue by Awilum** [doctrine/collections#245]
Is it possible to use **where** expression for multidimensional array ? 
https://www.doctrine-project.org/projects/doctrine-collections/en/1.6/expressions.html#where

I have such array(s):

```
...
array (
  'name' => 'Flextype',
  'version' => '0.9.8',
  'description' => 'Self-hosted Data-First Headless CMS & API.',
  'author' => 
  array (
    'name' => 'Sergey Romanenko',
    'email' => 'support@flextype.org',
    'url' => 'https://flextype.org',
  ),
  'homepage' => 'https://github.com/flextype',
  'bugs' => 'https://github.com/flextype/issues',
  'license' => 'MIT',
)
```

I want to find all records where **author** **name** is **Sergey Romanenko** is there is any simple way to do this ?
or I should make this array some how as a temporary flat array for search and than revert back to normal multidimensional  array ?

**Comment by Awilum** [comment]
okey, seems.. I have found solution https://github.com/flextype/flextype/commit/149324d63a6245f2178ba6f5ef6854cc1dd5d889

**Comment by SenseException** [comment]
There's currently no matching in a deeper level of an multidimensional array possible. Using an value object allows more approaches to access values with an comparison.
