### ISSUE TITLE
ClosureExpressionVisitor can not handle methods without the "get" prefix

### ISSUE THREAD

**Issue by gnumoksha** [doctrine/collections#276]
Hello. I'm wondering why there is a regular expression check here:

https://github.com/doctrine/collections/blob/94918256daa6ac99c7e5774720c0e76f01936bda/lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php#L55

I've methods that do not have "get" or "is" as a prefix, and they don't work because of that regex. Right now, I'm implementing the `__call` method on my object, but it would be nice if `ClosureExpressionVisitor` is able to find the methods.

**Comment by malarzm** [comment]
This was proposed (https://github.com/doctrine/collections/pull/149) and declined before, also there's  https://github.com/doctrine/collections/pull/263 still open so I'm closing this as a duplicate.
