### ISSUE TITLE
Use splice instead of unset in ArrayCollection

### ISSUE THREAD

**Issue by stollr** [doctrine/collections#297]
If items are removed from an `ArrayCollection` `unset` is used to remove the item from the underlying array. Is there a particular reason to use `unset`. There are some cases where it would be better if `splice` were used.

I'll show an example:

```php
$col = new ArrayCollection([$item]); // the collection's elements array looks like [0 => $item]
$col->removeElement($item);
$col->add($item); // the collection's elements array looks like [1 => $item]
```

Usually ths is no issue. But when serializing the collection to JSON. The result looks like

```json
{
    1: {id: 12, name: "example"}
}
```

instead of
```json
[
    {id: 12, name: "example"}
]
```

So this is a complete different result. 

But don't know how big the impact would be, if this would be changed to `splice`. What do you think?

**Comment by stollr** [comment]
Looks like this is related to #253

**Comment by derrabus** [comment]
It's a collection, not a list. What you are looking for is simply a different kind of data structure.

If it's just about the JSON serialization, you can still drop the keys if you don't need them. Collections expose a `getValues()` method for that purpose which delivers you a pure list of values.

**Comment by stollr** [comment]
Your argumentation would be correct if the collection were a map. Is it defined that way anywhere?

Maybe it would make sense to add a ListCollection then? What do you think?

**Comment by malarzm** [comment]
@naitsirch some (ok, long) time ago I've released https://github.com/malarzm/collections which provides more specific implementations of `Collection`, `ListArray` is one of them.

**Comment by malarzm** [comment]
> Your argumentation would be correct if the collection were a map. Is it defined that way anywhere?

Also, even if collection is not defined as a map "officially" (dunno) it is used as such by ODM and countless people that used it as such over the years. There's no way `ArrayCollection` can become a list instead of a map as that would be a massive BC break we're not going to make.

**Comment by derrabus** [comment]
> Your argumentation would be correct if the collection were a map. Is it defined that way anywhere?

As @malarzm already said, this is how ORM and ODM use the collection right now.

> Maybe it would make sense to add a ListCollection then? What do you think?

I'm not sure if we should add data structures just for the sake of it. If ORM and ODM do not make use of that data structure, it would be just dead code that we need to maintain.

**Comment by stollr** [comment]
Yes, it would only make sense if the collection type were configurable in ORM.
