### ISSUE TITLE
Criteria::expr() can be null - IDE is warning us

### ISSUE THREAD

**Issue by Lorddistrict** [doctrine/collections#299]
When using the `Criteria::expr()` static method, Phpstorm is telling me result can be null.
So I have to test result isn't null to avoid warning. When reading the class, we can see the property is not null :

```php
/**
 * Returns the expression builder.
 *
 * @return ExpressionBuilder
 */
public static function expr()
{
    if (self::$expressionBuilder === null) {
        self::$expressionBuilder = new ExpressionBuilder();
    }

    return self::$expressionBuilder;
}
```

Is it necessary to return this static property or could it be possible to return something we ensure which is not nullable ?

Or maybe, I have to test with an if statement if `expr()` result isn't null ?

**Comment by derrabus** [comment]
> Phpstorm is telling me result can be null.

Well, the method is annotated correctly. The method will never return `null` and `@return` annotation reflects that. If PhpStorm thinks otherwise, please open a bug report for PhpStorm.
