### ISSUE TITLE
Unable to resolve the template type TMaybeContained

### ISSUE THREAD

**Issue by garak** [doctrine/collections#346]
While running phpstan, I have this error in every part where I use `$myCollection->contains($myEntity)`:

>Unable to resolve the template type TMaybeContained in call to method Doctrine\Common\Collections\ReadableCollection<int,My\Entity>::contains()

At first I thought it could be a problem with my phpstan configuration, but the only mention I can found in the phpstan repo is in a [baseline file](https://github.com/phpstan/phpstan/blob/1.9.x/e2e/integration/doctrine-orm-baseline.neon)
The same file is telling that TMaybeContained "is not part of PHPDoc @template tags"

Is this problem resolvable in some way? Or am I forced to add such errors to my baseline?

**Comment by greg0ire** [comment]
Can you try reproducing it with https://phpstan.org/try ?

**Comment by garak** [comment]
> Can you try reproducing it with https://phpstan.org/try ?

Is that tool usable with external libraries? If so, I don't know how

**Comment by greg0ire** [comment]
No it isn't, I'm suggested you copy paste the code of `ReadableCollection` in there (just the necessary part)

**Comment by garak** [comment]
I tried this, but probably I messed up something https://phpstan.org/r/4bb0844b-499d-44b2-aff2-2467bb9eda62

**Comment by greg0ire** [comment]
I don't think you did, the error you get is ignored in our `phpstan.neon.dist`. If you don't get the same error on your local env, it means something is not the same.
Are you using the latest version of phpstan? Are you using phpstan/doctrine maybe? If yes, try removing it.

**Comment by garak** [comment]
Sorry, I forgot to add some basic info: phpstan 1.8.10 (currently the latest), level 6, no plugins.

**Comment by greg0ire** [comment]
I tried reproducing by copying `HelloWorld.php` directly in the library, and cannot reproduce the issue. Can you maybe create a PR with a file that has the issue? Let's close until you do.
