### ISSUE TITLE
Feature request: add a `find` method

### ISSUE THREAD

**Issue by florentdestremau** [doctrine/collections#356]
Similar to the javascript `Array.prototype.find`, this function would take a closure as a an argument and return the first item matching the closure.

Example:

```php
$collection = new ArrayCollection();

$itemToBeFound = $collection->find(fn ($item): bool => $item->getFoo() === 'bar');
```
`$item` here would be nullable.

**Comment by malarzm** [comment]
The function is already implemented: https://github.com/doctrine/collections/blob/425857d49df4812ca9199691d7d7aa66097d94f3/src/ReadableCollection.php#L216-L226

**Comment by florentdestremau** [comment]
this is only in the 2.0 version, is there a reason it's not included in earlier versions ?

**Comment by florentdestremau** [comment]
ok found this: https://github.com/doctrine/collections/pull/252#issuecomment-863368263

Not completely convinced but okay, fair enough
