### ISSUE TITLE
[2.1.1] Method `ArrayAccess::offsetExists()` might add `bool` as a native return type declaration in the future.

### ISSUE THREAD

**Issue by ruudk** [doctrine/collections#358]
I'm getting these deprecations when upgrading collections to 2.1.1:

* Method `Countable::count()` might add `int` as a native return type declaration in the future. Do the same in implementation `Doctrine\Common\Collections\AbstractLazyCollection` now to avoid errors or add an explicit @return annotation to suppress this message.
* Method `ArrayAccess::offsetExists()` might add `bool` as a native return type declaration in the future. Do the same in implementation `Doctrine\Common\Collections\AbstractLazyCollection` now to avoid errors or add an explicit @return annotation to suppress this message.
* Method `ArrayAccess::offsetGet()` might add `mixed` as a native return type declaration in the future. Do the same in implementation `Doctrine\Common\Collections\AbstractLazyCollection` now to avoid errors or add an explicit @return annotation to suppress this message.
* Method `ArrayAccess::offsetSet()` might add `void` as a native return type declaration in the future. Do the same in implementation `Doctrine\Common\Collections\AbstractLazyCollection` now to avoid errors or add an explicit @return annotation to suppress this message.
* Method `ArrayAccess::offsetUnset()` might add `void` as a native return type declaration in the future. Do the same in implementation `Doctrine\Common\Collections\AbstractLazyCollection` now to avoid errors or add an explicit @return annotation to suppress this message.
* Method `ArrayAccess::offsetGet()` might add `mixed` as a native return type declaration in the future. Do the same in implementation `Doctrine\ORM\PersistentCollection` now to avoid errors or add an explicit @return annotation to suppress this message.

But I don't understand it because `AbstractLazyCollection::offsetGet` has `#[ReturnTypeWillChange]`:
https://github.com/doctrine/collections/blob/425857d49df4812ca9199691d7d7aa66097d94f3/src/AbstractLazyCollection.php#L341-L347

Is this a bug in Symfony's Deprecation Helper?

**Comment by derrabus** [comment]
That's odd because we've released 2.1.1 exactly to address this issue.

**Comment by derrabus** [comment]
Okay, we've added the annotations Symfony's error handler asks for, but only on `ArrayCollection` and not `AbstractLazyCollection`. Would you mind sending a PR that fixes these issues?

**Comment by ruudk** [comment]
@derrabus It's added by @LVoogd in https://github.com/doctrine/collections/pull/359 🎉
