### ISSUE TITLE
Psalm annotations ArrayCollection->contains() incorrect

### ISSUE THREAD

**Issue by Hikariii** [doctrine/collections#368]
`ArrayCollection->contains()` defines a psalm template for `TMaybeContained` but does not define a param and return-type for that template. This gives the following psalm error:

```
Psalm output (using commit [d4c5f85](https://github.com/vimeo/psalm/commit/d4c5f85)): 

ERROR: [InvalidArgument](https://psalm.dev/004) - 68:17 - Argument 1 of ArrayCollection::contains expects TMaybeContained:fn-readablecollection::contains as mixed, but 3 provided
```

Psalm.dev example:
https://psalm.dev/r/aae16c4dc8

`ArrayCollection` either needs to not define `@template TMaybeContained` or re-define the psalm docblock from `ReadableCollection` completely.

`ArrayCollection->indexOf()` re-defines **all** psalm docblocks and works correctly because of that.

**Comment by Seros** [comment]
Hey,
could we please have a new release to resolve this for people who are using Psalm ^5.10 to make their and our CI pipeline work again?

**Comment by derrabus** [comment]
Sure, done. 🙂
