### ISSUE TITLE
Enum `Order` should be correctly handled as an enum

### ISSUE THREAD

**Issue by Aerendir** [doctrine/collections#404]
Currently, to use the enum we have to explicitly call the `->value`.

This seems to me to be useless as it would have been sufficient to simply use the Enum and let the code handle the conversion to string.

```diff
class MyEntity
{
    ...

-    #[OrderBy(['opened' => Order::Descending->value])]
+    #[OrderBy(['opened' => Order::Descending])]
    private Collection $orderableItems;
```

**Comment by derrabus** [comment]
The `OrderBy` attribute is not part of the collections library.

**Comment by Aerendir** [comment]
@derrabus , you are right: sorry.

I also found an issue already opened about this:

- https://github.com/doctrine/orm/issues/11313
