### ISSUE TITLE
missing flatMap() method on collection.

### ISSUE THREAD

**Issue by antanas-arvasevicius** [doctrine/collections#70]
There are many cases where this would be useful: e.g. in pseudo code

```typescript
var allUserOrders = user.invoices.flatMap((invoice) => return invoice.orders);
```
now it's not possible to do that with current `Collection` API. We need to convert collections to arrays and apply array_reduce, or array_merge. or just use foreach loops and create new collection.

```php
$invoicesOrders = $user->invoices->map(function ($item) { return $item->orders()->toArray(); })->toArray();

$allUserOrders = [];
foreach ($invoicesOrders as $orders) { $allUserOrders = array_merge($allUserOrders, $orders); }

return new ArrayCollection($allUserOrders);
```

**Comment by Ocramius** [comment]
The `Collection` API is closed for modifications in 2.x (due to BC concerns). Adding anything to it is a BC break, sorry :-\
