### ISSUE TITLE
Change remove method name to a more semantic one

### ISSUE THREAD

**Issue by DonCallisto** [doctrine/collections#94]
Take a look at this

```
/**
 * {@inheritDoc}
 */
public function remove($key)
{
    if ( ! isset($this->elements[$key]) && ! array_key_exists($key, $this->elements)) {
        return null;
    }
    $removed = $this->elements[$key];
    unset($this->elements[$key]);
    return $removed;
}
```

this is `remove` operation of `ArrayCollection`.

There is also a `removeElement` operation that, sometimes, is just confused with `remove` (eg.: you try to `remove` an Object instead of *that* object by its id, using `remove` and not `removeElement`)

Can't we refactor this name into a more semantic one, like `removeElementById`?
Personally I find this more clear and less error prone.

We can initially deprecate it to the advantage of the new one and in future, as it will be a BC one, integrate in new major version.

Let me know if I can open a pull request.

**Comment by Ocramius** [comment]
@DonCallisto adding a method and deprecating the existing one is unfeasible due to BC boundaries.

**Comment by DonCallisto** [comment]
@Ocramius Roger that.
